### ISSUE TITLE
version 에러가 발생합니다.

### ISSUE THREAD

**Issue by thesailman** [ilotoki0804/WebtoonScraper#1]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Scripts\webtoon.exe\__main__.py", line 4, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\WebtoonScraper\__init__.py", line 12, in <module>
    from .base import (
ImportError: cannot import name '__version_info__' from 'WebtoonScraper.base' (C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\WebtoonScraper\base.py). Did you mean: '__version__'?

파이썬 3.1.2며, 스크래퍼 버전은 현재나온 최신버전입니다.
py로 실행하거나, 아니면 cmd로 실행시에도 해당 에러가 뜹니다.

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\download_webtoon.py", line 1, in <module>
    from WebtoonScraper.scrapers import LezhinComicsScraper
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\WebtoonScraper\__init__.py", line 12, in <module>
    from .base import (
ImportError: cannot import name '__version__' from 'WebtoonScraper.base' (C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\WebtoonScraper\base.py)

py실행시 에러문구입니다

**Comment by ilotoki0804** [comment]
고쳐졌습니다. `pip install WebtoonScraper[full] -U`로 업데이트하시면 됩니다.

**Comment by thesailman** [comment]
C:\Users\Administrator>webtoon download "https://www.lezhin.com/ko/comic/narcissus" --options bearer="Bearer 37f0b7ad-f8a7-4352-ac96-3f9297cdfee1" unshuffle=false
ERROR    KeyError: 'imageShuffle'

수정후 업뎃하였으나, 해당에러가 발생합니다. 뒤에 unshuffle=false 붙여도 안됩니다.

**Comment by thesailman** [comment]
> 고쳐졌습니다. `pip install WebtoonScraper[full] -U`로 업데이트하시면 됩니다.

C:\Users\Administrator>webtoon download "https://www.lezhin.com/ko/comic/narcissus" --options bearer="@@@@@@@@@@" unshuffle=false
ERROR KeyError: 'imageShuffle'

수정후 업뎃하였으나, 해당에러가 발생합니다. 뒤에 unshuffle=false 붙여도 안됩니다.
이는 해당웹툰이 셔플된 상태가 아니라서, 발생하는듯 합니다. 해당웹툰이 아닌 다른웹툰, 즉 셔플된 웹툰은 작동합니다

**Comment by ilotoki0804** [comment]
4.1.2에서 고쳐졌습니다. `pip install WebtoonScraper[full] -U`로 업데이트하시면 됩니다.

**Comment by thesailman** [comment]
> 4.1.2에서 고쳐졌습니다. `pip install WebtoonScraper[full] -U`로 업데이트하시면 됩니다.

Successfully retrieved: 'https://www.lezhin.com/lz-api/v2/cloudfront/signed-url/generate?contentId=6174950587957248&episodeId=6519289945456640&purchased=false&q=30&firstCheckType=P'
downloading '외전 2화 세희의 이야기':  96%|██████████████████████████████████████████▏ | 71/74 [05:48<00:14,  4.90s/it]
ERROR    InvalidURL: Invalid non-printable ASCII character in URL

C:\Users\Administrator>webtoon download "https://www.lezhin.com/ko/comic/narcissus" --options bearer="예문dfee1"
INFO     Webtoon data are fetched. Download has been started...
'외전 2화 세희의 이야기' skipped:  96%|█████████████████████████████████████████████  | 71/74 [00:00<00:00, 157.55it/s]]
ERROR    InvalidURL: Invalid non-printable ASCII character in URL

C:\Users\Administrator>webtoon download "https://www.lezhin.com/ko/comic/narcissus" --options bearer="예문 -r 40~
INFO     Webtoon data are fetched. Download has been started...
'외전 2화 세희의 이야기' skipped:   1%|▋                                                | 1/74 [00:00<00:09,  7.87it/s]WARNING  can't retrieve data from 외전 3화 도은이의 이야기. It's probably because Episode is not available or not for
         free episode.
WARNING  Failed to download: 72. 외전 3화 도은이의 이야기
'외전 3화 도은이의 이야기' download failed:  97%|████████████████████████████████████ | 72/74 [00:00<00:00, 245.18it/s]WARNING  can't retrieve data from 외전 4화 효은이의 이야기. It's probably because Episode is not available or not for
         free episode.
WARNING  Failed to download: 73. 외전 4화 효은이의 이야기
'외전 4화 효은이의 이야기' download failed:  97%|████████████████████████████████████ | 72/74 [00:01<00:00, 245.18it/s]WARNING  can't retrieve data from 외전 최종화 규리의 이야기. It's probably because Episode is not available or not for
         free episode.
WARNING  Failed to download: 74. 외전 최종화 규리의 이야기
'외전 최종화 규리의 이야기' download failed: 100%|█████████████████████████████████████| 74/74 [00:02<00:00, 30.11it/s]
INFO     The webtoon 선화의 그늘가 download ended.

C:\Users\Administrator>webtoon download "https://www.lezhin.com/ko/comic/narcissus" --options bearer="예문 -r 40~
INFO     Webtoon data are fetched. Download has been started...
'외전 2화 세희의 이야기' skipped:   1%|▋                                                | 1/74 [00:00<00:09,  7.87it/s]WARNING  can't retrieve data from 외전 3화 도은이의 이야기. It's probably because Episode is not available or not for
         free episode.
WARNING  Failed to download: 72. 외전 3화 도은이의 이야기
'외전 3화 도은이의 이야기' download failed:  97%|████████████████████████████████████ | 72/74 [00:00<00:00, 257.08it/s]WARNING  can't retrieve data from 외전 4화 효은이의 이야기. It's probably because Episode is not available or not for
         free episode.
WARNING  Failed to download: 73. 외전 4화 효은이의 이야기
'외전 4화 효은이의 이야기' download failed:  97%|████████████████████████████████████ | 72/74 [00:00<00:00, 257.08it/s]WARNING  can't retrieve data from 외전 최종화 규리의 이야기. It's probably because Episode is not available or not for
         free episode.
WARNING  Failed to download: 74. 외전 최종화 규리의 이야기
'외전 최종화 규리의 이야기' download failed: 100%|█████████████████████████████████████| 74/74 [00:00<00:00, 99.24it/s]
INFO     The webtoon 선화의 그늘가 download ended.

C:\Users\Administrator>webtoon download -r 40~ "https://www.lezhin.com/ko/comic/narcissus" --options bearer="예문
INFO     Webtoon data are fetched. Download has been started...
'외전 2화 세희의 이야기' skipped:  91%|███████████████████████████████████████████▉    | 32/35 [00:00<00:00, 70.08it/s]]
ERROR    KeyError: 'data'

C:\Users\Administrator>webtoon download "https://www.lezhin.com/ko/comic/narcissus" --options bearer="예문
INFO     Webtoon data are fetched. Download has been started...
'외전 2화 세희의 이야기' skipped:  96%|█████████████████████████████████████████████  | 71/74 [00:00<00:00, 149.00it/s]]
ERROR    KeyError: 'data'

https://www.lezhin.com/ko/comic/narcissus
현재 무료로 전체가 풀려있으나, 스크래퍼가 무료 아니라고 작동이 안됩니다. 전체다운으로 했더니 에러가 떠서 특정범위 지정으로 하면 key error - data 가 뜹니다

**Comment by ilotoki0804** [comment]
이제 작동할 겁니다. 업데이트해보세요.

**Comment by thesailman** [comment]
> 이제 작동할 겁니다. 업데이트해보세요.

INFO     Webtoon data are fetched. Download has been started...
'외전 2화 세희의 이야기' skipped:   1%|▋                                                | 1/74 [00:00<00:11,  6.62it/s]WARNING  can't retrieve data from 외전 3화 도은이의 이야기. It's probably because Episode is not available or not for
         free episode.
WARNING  Failed to download: 72. 외전 3화 도은이의 이야기
'외전 3화 도은이의 이야기' download failed:  97%|████████████████████████████████████▉ | 72/74 [00:01<00:00, 61.16it/s]WARNING  can't retrieve data from 외전 4화 효은이의 이야기. It's probably because Episode is not available or not for
         free episode.
WARNING  Failed to download: 73. 외전 4화 효은이의 이야기
'외전 4화 효은이의 이야기' download failed:  97%|████████████████████████████████████▉ | 72/74 [00:02<00:00, 61.16it/s]WARNING  can't retrieve data from 외전 최종화 규리의 이야기. It's probably because Episode is not available or not for
         free episode.
WARNING  Failed to download: 74. 외전 최종화 규리의 이야기
'외전 최종화 규리의 이야기' download failed: 100%|█████████████████████████████████████| 74/74 [00:03<00:00, 21.76it/s]
INFO     The webtoon 선화의 그늘가 download ended.

일단 오늘중으로 유료화가 되긴 하겠으나, 아직 무료회차임에도 불구하고, 자꾸 다운로드 failed가 발생합니다

**Comment by ilotoki0804** [comment]
혹시 bearer를 빠뜨리시고 다운로드하신 건 아닌가요?

**Comment by ilotoki0804** [comment]
확인했습니다.

**Comment by thesailman** [comment]
> 이메일 좀 알려주세요

아.. 뒤에 -r붙이면서 베어러뒤에 "안붙였네요 죄송합니다.

이메일 jeoungkuyoon@gmail.com입니다

**Comment by thesailman** [comment]
***@***.*** 입니다

2024년 9월 14일 (토) 오후 7:08, ilotoki0804 ***@***.***>님이 작성:

**Comment by thesailman** [comment]
> 확인했습니다.

아 감사합니다.. 보내주실줄은 몰랐는데.. 도움에 감사드립니다.

**Comment by thesailman** [comment]
> 확인했습니다.

안녕하세요. 오랜만에 문의드립니다. 업데이트 이후로 생긴 문제인 것인지, 아님 오류가 발생한 것인지는 모르겠습니다만, 카카오웹툰 인식방식에 차이가 생긴듯 합니다.

ERROR    InvalidPlatformError: Platform not detected:
         https://webtoon.kakao.com/content/%EB%B9%84%EB%B0%80-%EC%A4%84%EB%A6%AC%EC%97%A3/3572?tab=episode
PS C:\Users\jeoun> https://webtoon.kakao.com/content/%EB%B9%84%EB%B0%80-%EC%A4%84%EB%A6%AC%EC%97%A3/3572?tab=episode
https://webtoon.kakao.com/content/%EB%B9%84%EB%B0%80-%EC%A4%84%EB%A6%AC%EC%97%A3/3572?tab=episode : 'https://webtoon.ka
kao.com/content/%EB%B9%84%EB%B0%80-%EC%A4%84%EB%A6%AC%EC%97%A3/3572?tab=episode' 용어가 cmdlet, 함수, 스크립트 파일 또
는 실행할 수 있는 프로그램 이름으로 인식되지 않습니다. 이름이 정확한지 확인하고 경로가 포함된 경우 경로가 올바른지 검증
한 다음 다시 시도하십시오.
위치 줄:1 문자:1
+ https://webtoon.kakao.com/content/%EB%B9%84%EB%B0%80-%EC%A4%84%EB%A6% ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (https://webtoon...572?tab=episode:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\jeoun> webtoon download "https://webtoon.kakao.com/content/%EB%B9%84%EB%B0%80-%EC%A4%84%EB%A6%AC%EC%97%A3/3572?tab=episode"
ERROR    InvalidPlatformError: Platform not detected:
         https://webtoon.kakao.com/content/%EB%B9%84%EB%B0%80-%EC%A4%84%EB%A6%AC%EC%97%A3/3572?tab=episode
PS C:\Users\jeoun> webtoon download https://comic.naver.com/webtoon/list?titleId=814885
INFO     Fetching metadata...
INFO     Downloading '그 남학생에게 고백하지...'...
downloading '후기': 100%|██████████████████████████████████████████████████████████████| 52/52 [01:54<00:00,  2.20s/it]
INFO     The webtoon 그 남학생에게 고백하지 마십시오 download ended.
PS C:\Users\jeoun>

네이버는 작동하나, 카카오웹툰은 플랫폼을 인식을 못하더라고요. cmd로 실행하는 pip 재설치와 업데이트, 후원으로  보급받은 gui와 app 모두 작동이 안됩니다. 
급한대로 히토미 다운로더 이용해서 받았으며, 아마도 인식오류가 발생한듯 합니다. 다음 업데이트때 수정해주시면 감사드리겠습니다.

**Comment by ilotoki0804** [comment]
포터블 버전을 사용하면 어떤 오류 메시지가 나오나요?

**Comment by thesailman** [comment]
> 포터블 버전을 사용하면 어떤 오류 메시지가 나오나요?

포터블 버전을 사용시, 다운이 안됨에도 불구하고 작업이 완료되었다고 뜹니다. 들어가보면 json파일및 이미지 파일밖에 없었씁니다

**Comment by ilotoki0804** [comment]
`webtoon -v download "<url>"`로 실행하신 뒤에 전체 로그를 보여주실 수 있나요?

**Comment by thesailman** [comment]
> `webtoon -v download "<url>"`로 실행하신 뒤에 전체 로그를 보여주실 수 있나요?

C:\Users\jeoun>webtoon -v download "https://webtoon.kakao.com/content/%EC%82%B0%ED%83%80-%EC%9D%B8%EB%8D%94%EC%8A%A4%ED%8A%B8%EB%A6%AC/3629"
ERROR    InvalidPlatformError: Platform not detected:
         https://webtoon.kakao.com/content/%EC%82%B0%ED%83%80-%EC%9D%B8%EB%8D%94%EC%8A%A4%ED%8A%B8%EB%A6%AC/3629
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\Lib\site-packages\WebtoonScraper\__main__.py:291 in main                                      │
│                                                                                                  │
│   288 │   try:                                                                                   │
│   289 │   │   match args.subparser_name:                                                         │
│   290 │   │   │   case "download":                                                               │
│ ❱ 291 │   │   │   │   parse_download(args)                                                       │
│   292 │   │   │   case unknown_subparser:                                                        │
│   293 │   │   │   │   raise NotImplementedError(f"{unknown_subparser} is not a valid command."   │
│   294 │   except KeyboardInterrupt as exc:                                                       │
│                                                                                                  │
│ D:\Lib\site-packages\WebtoonScraper\__main__.py:228 in parse_download                            │
│                                                                                                  │
│   225                                                                                            │
│   226 def parse_download(args: argparse.Namespace) -> None:                                      │
│   227 │   for webtoon_id in args.webtoon_ids:                                                    │
│ ❱ 228 │   │   scraper = setup_instance(                                                          │
│   229 │   │   │   webtoon_id,                                                                    │
│   230 │   │   │   args.platform,                                                                 │
│   231 │   │   │   cookie=args.cookie,                                                            │
│                                                                                                  │
│ D:\Lib\site-packages\WebtoonScraper\__main__.py:208 in setup_instance                            │
│                                                                                                  │
│   205 │                                                                                          │
│   206 │   # 스크래퍼 불러오기                                                                    │
│   207 │   if webtoon_platform == "url" or "." in webtoon_id_or_url:  # URL인지 확인              │
│ ❱ 208 │   │   scraper = instantiate_from_url(webtoon_id_or_url)                                  │
│   209 │   else:                                                                                  │
│   210 │   │   scraper = instantiate(webtoon_platform, webtoon_id_or_url)                         │
│   211                                                                                            │
│                                                                                                  │
│ D:\Lib\site-packages\WebtoonScraper\__main__.py:192 in instantiate_from_url                      │
│                                                                                                  │
│   189 │   │   except InvalidURLError:                                                            │
│   190 │   │   │   continue                                                                       │
│   191 │   │   return platform                                                                    │
│ ❱ 192 │   raise InvalidPlatformError(f"Platform not detected: {webtoon_url}")                    │
│   193                                                                                            │
│   194                                                                                            │
│   195 def setup_instance(                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
InvalidPlatformError: Platform not detected:
https://webtoon.kakao.com/content/%EC%82%B0%ED%83%80-%EC%9D%B8%EB%8D%94%EC%8A%A4%ED%8A%B8%EB%A6%AC/3629

이렇게 나옵니다

**Comment by ilotoki0804** [comment]
동일한 명령어를 포터블 버전을 실행했을 때는 어떻게 나오나요?

**Comment by thesailman** [comment]
> 동일한 명령어를 포터블 버전을 실행했을 때는 어떻게 나오나요?

>>> webtoon -v download "https://webtoon.kakao.com/content/%EC%82%B0%ED%83%80-%EC%9D%B8%EB%8D%94% EC%8A%A4%ED%8A%B8%EB%A6%AC/3629"
INFO     Fetching metadata...
DEBUG    <function KakaoWebtoonScraper.fetch_episode_information at 0x0000023E62441940> is already loaded, so loading is
         skipped. In order to reload, set `reload` parameter to True.
DEBUG    WebtoonScraper status: setup, context: {'finishing': True, 'is_successful': True}
DEBUG    WebtoonScraper status: download_thumbnail, context: {'finishing': False}
INFO     Downloading '페이지를 찾을 수 없습니다.'...
DEBUG    WebtoonScraper status: download_episode, context: {'finishing': False}
  0%|                                                                                           | 0/62 [00:00<?, ?it/s]
ERROR    Finalizing...
ERROR    MissingOptionalDependencyError: Package 'pycryptodomex' is not installed in Python environment. Please install
         'pycryptodomex' though one of following command:
         pip install -U WebtoonScraper[full]  (RECOMMENDED; download every extra dependency)
         pip install -U WebtoonScraper[kakao_webtoon]  (minimal; download required dependency for this particular
         download)
         pip install -U pycryptodomex  (download manually, not recommended since it could install incompatible version)
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in importing:119                                                                                 │
│                                                                                                  │
│ in _load_cryptodome:37                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'Cryptodome'

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in main:367                                                                                      │
│                                                                                                  │
│ in parse_download:266                                                                            │
│                                                                                                  │
│ in download_webtoon:171                                                                          │
│                                                                                                  │
│ in run:190                                                                                       │
│                                                                                                  │
│ in run:118                                                                                       │
│                                                                                                  │
│ in run_until_complete:654                                                                        │
│                                                                                                  │
│ in async_download_webtoon:216                                                                    │
│                                                                                                  │
│ in _download_episodes:399                                                                        │
│                                                                                                  │
│ in _download_episode:469                                                                         │
│                                                                                                  │
│ in get_episode_image_urls:179                                                                    │
│                                                                                                  │
│ in _load_cryptodome:36                                                                           │
│                                                                                                  │
│ in __exit__:158                                                                                  │
│                                                                                                  │
│ in importing:131                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
MissingOptionalDependencyError: Package 'pycryptodomex' is not installed in Python environment. Please install
'pycryptodomex' though one of following command:
pip install -U WebtoonScraper[full]  (RECOMMENDED; download every extra dependency)
pip install -U WebtoonScraper[kakao_webtoon]  (minimal; download required dependency for this particular download)
pip install -U pycryptodomex  (download manually, not recommended since it could install incompatible version)



--------------------
업데이트를 해도 pycryptodomex 없다고 자꾸 나옵니다

pip full 도 해보고 pip pycryptodomex 도 해봤습니다

**Comment by ilotoki0804** [comment]
연락이 늦어져서 죄송합니다. 해당 문제는 현재 고쳐졌고 며칠 내로 배포될 WebtoonScraper 5에서 해결될 예정닙니다.

**Comment by thesailman** [comment]
> 연락이 늦어져서 죄송합니다. 해당 문제는 현재 고쳐졌고 며칠 내로 배포될 WebtoonScraper 5에서 해결될 예정닙니다.

감사합니다. 유료화 전작품 오늘 작동해보니 잘 됩니다. 그리고 레진코믹스 bearer 요청 엔드포인트가 바뀐건지, get bearer 쓰면 인식 못하는것도 있고 f12 개발자에서도 bearer 가 안뜨던데 나중에 확인부탁드려도 되곘습니까?

**Comment by ilotoki0804** [comment]
알겠습니다. 확인해 보겠습니다.

**Comment by ilotoki0804** [comment]
해결됐습니다!

**Comment by thesailman** [comment]
> 해결됐습니다!

get bearer 쓰니 이제 bearer 가 정상적으로 뽑혀나옵니다!! 감사합니다!!

WebtoonScraper: error: unrecognized arguments: --options bearer=B@

C:\Users\jeoun>webtoon download "https://www.lezhin.com/ko/comic/sami" --option bearer="B@
8d4d4b40eb5"
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\Lib\site-packages\WebtoonScraper\__main__.py:311 in async_main                                │
│                                                                                                  │
│   308 │   │   try:                                                                               │
│   309 │   │   │   match args.subparser_name:                                                     │
│   310 │   │   │   │   case "download":                                                           │
│ ❱ 311 │   │   │   │   │   await parse_download(args)                                             │
│   312 │   │   │   │   case unknown_subparser:                                                    │
│   313 │   │   │   │   │   raise NotImplementedError(f"{unknown_subparser} is not a valid comma   │
│   314 │   │   except KeyboardInterrupt as exc:                                                   │
│                                                                                                  │
│ D:\Lib\site-packages\WebtoonScraper\__main__.py:240 in parse_download                            │
│                                                                                                  │
│   237 │   │   │   args.platform,                                                                 │
│   238 │   │   │   cookie=args.cookie,                                                            │
│   239 │   │   │   download_directory=args.base_directory,                                        │
│ ❱ 240 │   │   │   options=dict(args.options or {}),                                              │
│   241 │   │   │   existing_episode_policy=args.existing_episode,                                 │
│   242 │   │   )                                                                                  │
│   243                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'options'

C:\Users\jeoun>webtoon download "https://www.lezhin.com/ko/comic/sami" --options bearer="B@5"
usage: WebtoonScraper [-h] [--mock] [-v] [--propagate-error] [--no-progress-bar] [-N THREAD_NUMBER] [--version]
                      {download} ...
WebtoonScraper: error: unrecognized arguments: --options bearer=Bearer @

다만 업뎃하면서 options를 option으로 바뀌는 과정에서 인식이 잘못되었는지, namespace 는 options로 뜨더라고요, 확인한번 해주시면 감사하겠습니다.

**Comment by thesailman** [comment]
> 해결됐습니다!

혹시나 해서 질문드리는데, cmd 키고 webtoon download "해당 레진코믹 링크" --option bearer="Bearer ~~" 하는게 맞는걸까요?

**Comment by ilotoki0804** [comment]
수정됐습니다. `pip install -U WebtoonScraper`로 업데이트하시면 됩니다.

**Comment by thesailman** [comment]
> 수정됐습니다. `pip install -U WebtoonScraper`로 업데이트하시면 됩니다.

감사합니다!
