### ISSUE TITLE
unrecognized arguments가 뜹니다

### ISSUE THREAD

**Issue by marienjayma** [ilotoki0804/WebtoonScraper#12]
안녕하세요 지금까지 너무 감사했습니다 

webtoon download crown. -plezhin_comics --bearer "******"

이렇게 입력했었습...   . 다 
bearer 안하면 1-2화는 성공적으로 다운됩니다 
usage: WebtoonScraper [-h] [--mock] [--version] [-v]
               {download,merge,concat} ...
WebtoonScraper: error: unrecognized arguments: --bearer ********

근데 이 문장이 뜨고 다운로드가 안됩니다 
제발 마지막으로 도움주시면 정말 너무 감사드리겠습니다 
제 bearer가 잘못된것인지 bearer 명령이 안되는건지 알려주시면 감사하겠습니다

**Comment by thesailman** [comment]
오옷 저같은 상황이네요. 칼날왕관 받으시고 계시죠? 저도 뒤에 bearer붙이면 에러떠서 제작자님께 문의남겨놨습니다.

저같은경우는 .py로 파일 만든다음에 제작자님께서 알려주신 구문 작성해서
[download_webtoon - 복사본.zip](https://github.com/user-attachments/files/16569227/download_webtoon.-.zip)
이렇게 해서 실행시켜서 unshuffle까지 작동시켰습니다.

https://github.com/ilotoki0804/WebtoonScraper/issues/9
다운받기 불안하시면 해당이슈에 제작자님 가르쳐주신 사안 참고하시는것도 추천드립니다.

**Comment by ilotoki0804** [comment]
WebtoonScraper 4에서 bearer를 처리하는 방식이 달라져서 그렇습니다.
WebtoonScraper 4부터는 다음과 같이 코드를 짜야 합니다.
```console
webtoon download "<다운로드받을 웹툰 URL>" --options bearer="Bearer ..."
```

**Comment by marienjayma** [comment]
> WebtoonScraper 4에서 bearer를 처리하는 방식이 달라져서 그렇습니다. WebtoonScraper 4부터는 다음과 같이 코드를 짜야 합니다.
> 
> ```
> webtoon download "<다운로드받을 웹툰 URL>" --options bearer="Bearer ..."
> 
webtoon download "https://www.lezhin.com/ko/comic/crown" options bearer="제 bearer 입력" download_paid=true

알려주신대로 저렇게 입력했더니 다운로드가 시작되긴했는데 1,2화 빼고는 failed to download가 뜹니다

WARNING  Failed to download: 39. 난세                                           
'난세' download failed:  93%|█████████████████▋ | 39/42 [00:34<00:02,  1.07it/s]WARNING  can't retrieve data from 해는 숨어들고. It's probably because Episode  
         is not available or not for free episode.                              
WARNING  Failed to download: 40. 해는 숨어들고                                  
'해는 숨어들고' download failed:  95%|█████████▌| 40/42 [00:35<00:01,  1.04it/s]WARNING  can't retrieve data from 최종화 : 역사의 나선. It's probably because   
         Episode is not available or not for free episode.                      
WARNING  Failed to download: 41. 최종화 : 역사의 나선                           
'최종화 : 역사의 나선' download failed:  98%|██▉| 41/42 [00:36<00:00,  1.06it/s]WARNING  can't retrieve data from 완결 후기. It's probably because Episode is   
         not available or not for free episode.                                 
WARNING  Failed to download: 42. 완결 후기                                      
'완결 후기' download failed: 100%|██████████████| 42/42 [00:37<00:00,  1.12it/s]
INFO     The webtoon 칼날왕관 download ended.     

혹시 왜 그런건가요 항상 너무 감사드립니다

**Comment by marienjayma** [comment]
> 오옷 저같은 상황이네요 다행히 저만 그런게 아니었군요. 칼날왕관 받으시고 계시죠? 저도 뒤에 bearer붙이면 cmd나 파이썬 둘다 에러떠서 제작자님께 문의남겨놨습니다.
> 
> 저같은경우는 .py로 파일 만든다음에 제작자님께서 알려주신 구문 작성해서 실행시켜서 unshuffle까지 작동시켰습니다.

제작자님이 새로 알려주신 코드로 해봤는데도 다운이 안되더라구요
.py 파일 만드는거 시도해볼려고 하는데 어렵네요
그래도 알려주셔서 정말 감사합니다

**Comment by ilotoki0804** [comment]
@marienjayma
`--options`라고 써야 하는데 그냥 `options`라고 쓰셔서 그런 것 같습니다.

```console
webtoon download "<다운로드받을 웹툰 URL>" --options bearer="Bearer ..."
```

**Comment by marienjayma** [comment]
> @marienjayma `--options`라고 써야 하는데 그냥 `options`라고 쓰셔서 그런 것 같습니다.
> 
> ```
> webtoon download "<다운로드받을 웹툰 URL>" --options bearer="Bearer ..."
> ```
제작자님 드디어 다운로드가 성공적으로 됐습니다 이틀동안 너무 감사했습니다
친절하게 알려주셔서 정말 고마웠습니다
