### ISSUE TITLE
레진 웹툰 다운로드가 현재 안되는 것 같습니당!

### ISSUE THREAD

**Issue by maeng-jin** [ilotoki0804/WebtoonScraper#13]
레진 UIUX가 개편 되 것 같은데 그것 때문일까용!?

**Comment by ilotoki0804** [comment]
맞습니다. 해당 문제가 프리릴리즈에서는 해결되어서 업데이트하신 뒤 다음의 명령어로 다운로드받으실 수 있습니다.

프리릴리즈로 업데이트는 다음의 명령어로 하시면 됩니다.

```console
pip install WebtoonScraper[full] --pre -U
```

그런 다음 다음의 명령어를 사용하면 됩니다.

```console
webtoon download "<웹툰 URL>" --options bearer="<자신의 bearer>"
```

WebtoonScraper 4부터는 bearer를 적용하는 방식이 `--options bearer="<bearer>"`로 변경되었으니 참고하세요.
