### ISSUE TITLE
레진코믹스 1080p 지원 및 모든 rating 지원

### ISSUE THREAD

**Issue by kkkkk-123** [ilotoki0804/WebtoonScraper#3]
구매한 작품들을 다운로드하고 싶은데 성인 작품들만 에러가 뜹니다. 성인 작품은 다운로드할 수 없는 건가요?
추가로 궁금한 점이 있는데, 구매한 작품은 가로 해상도 1080px로 제공되는데 720px로 받아지더군요.. 1080px로 받을 수는 없을까요?

**Comment by ilotoki0804** [comment]
오류 메시지와 사용한 코드나 cli 명령어를 제공해주실 수 있나요? 개인정보가 있는 부분은 제거해서 제공해 주세요.
구매한 에피소드 관련 내용은 한 번 확인해 보겠습니다.

**Comment by ilotoki0804** [comment]
구매한 에피소드에 대해 1080p로 다운로드받을 수 있는 기능이 방금 커밋되었습니다. 다음 릴리즈에서 반영될 예정입니다.

**Comment by kkkkk-123** [comment]
감사합니다!! 개인정보로 보이는 부분은 지웠어요.

코드
from WebtoonScraper.scrapers import LezhinComicsScraper

authkey = 'Bearer ...'
scraper = LezhinComicsScraper('paintings', authkey=authkey)  # 자신이 구매한 유료 회차가 있는 웹툰을 gahu_r의 위치에 붙여넣으세요.
scraper.get_paid_episode = True
scraper.download_webtoon()

오류 메시지
Traceback (most recent call last):
  File "C:\Users\USER\test\lezhin.py", line 6, in <module>
    scraper.download_webtoon()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\WebtoonScraper\scrapers\A_scraper.py", line 299, in download_webtoon
    self.setup()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\WebtoonScraper\scrapers\A_scraper.py", line 451, in setup
    self.fetch_episode_informations(reload=reload)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\WebtoonScraper\scrapers\A_scraper.py", line 54, in wrapper
    return_value = f(self, *args, reload=reload, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\WebtoonScraper\scrapers\J_lezhin_comics.py", line 95, in fetch_episode_informations
    title = res.soup_select_one("h2.comicInfo__title", no_empty_result=True).text
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\resoup\souptools.py", line 184, in soup_select_one
    raise EmptyResultError(
resoup.exceptions.EmptyResultError: Result of select_one is None. This error happens probably because of invalid selector or URL. Check if both selector and URL are valid. Set to False `no_empty_result` if empty list is intended. It may also because of selector is not matched with URL.
selector: 'h2.comicInfo__title', URL: https://www.lezhin.com/ko/login?redirect=%2Fko%2Fadult%3Fredirect%3D%252Fko%252Fcomic%252Fpaintings

**Comment by ilotoki0804** [comment]
2.3.4가 방금 릴리즈되었습니다. 업데이트하시고 [버프툰 다운로드하기](https://github.com/ilotoki0804/WebtoonScraper/blob/master/docs/specific_platform_download.md#%EB%B2%84%ED%94%84%ED%88%B0-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C%ED%95%98%EA%B8%B0) 파트에 있는 내용을 참고해서 cookie를 취득한 다음 다음 코드에 통합해서 확인해주실 수 있나요?
```python
from WebtoonScraper.scrapers import LezhinComicsScraper

authkey = "Bearer ..."
cookie = "cookie here"

scraper = LezhinComicsScraper("paintings", authkey=authkey, cookie=cookie)
scraper.download_webtoon()
```

**Comment by kkkkk-123** [comment]
반영해 주셔서 감사합니다. 그런데 쿠키 취득하려니 버프툰과 다르게 cookie가 보이지 않는데 어디서 취득해야 할까요ㅠㅠ?

**Comment by ilotoki0804** [comment]
> 반영해 주셔서 감사합니다. 그런데 쿠키 취득하려니 버프툰과 다르게 cookie가 보이지 않는데 어디서 취득해야 할까요ㅠㅠ?

쿠키를 찾는 방법은 다음과 같습니다.
1. 웹툰 페이지로 갑니다.
2. 우선 f12를 누르고 `네트워크` 탭으로 갑니다.
3. f5를 누릅니다.
4. 스크롤을 맨 위로 올려서 첫 번째 request를 클릭합니다.
5. 아래로 내려서 `요청 헤더`로 갑니다(주의: '응답 헤더'가 아닙니다!)
6. 요청 헤더에서 아래로 스크롤하다 보면 `Cookie:`라고 되어 있는 란이 뜹니다.
7. 쿠키를 복사합니다.

> 쿠키가 어디에 있는지 몰라서 cookie가 있는 것만 찾아서 전부 다 테스트를 해 봤는데 무료로 공개된 회차만 받아지네요...!

cookie와 authkey를 **모두** 설정하셨나요? authkey가 설정되지 않았다면 무료로 공개된 회차만 받아집니다.

**Comment by kkkkk-123** [comment]
감사합니다!! 1080px로 잘 받아지네요. 유용히 잘 쓸게요. 새해 복 많이 받으세요 :)

**Comment by ilotoki0804** [comment]
> 제가 무료 회차도 전부 구매했는데 2화부터 1080px로 받아지네요ㅠㅠ.. 다른 작품도 동일하게 2화부터 1080px이에요.
1화나 후기 같은 건 720px로 받아지는데 1080px로 받을 방법이 없을까요?!

방금 2.3.5를 릴리즈했습니다. 업데이트 하시고 다음의 코드를 한 번 사용해 보세요.
```python
from WebtoonScraper.scrapers import LezhinComicsScraper

if __name__ == "__main__":
    bearer = 'Bearer ...'
    scraper = LezhinComicsScraper('gahu_r', bearer=bearer)  # 소장한 무료 에피소드가 있는 웹툰을 gahu_r의 위치에 붙여넣으세요.
    scraper.get_paid_episode = True
    scraper.fetch_user_infos()
    scraper.download_webtoon()
```

**Comment by kkkkk-123** [comment]
고생하셨습니다! 여전히 무료 공개 회차는 구매를 했음에도 720px로 받아지네요. 
![1080](https://github.com/ilotoki0804/WebtoonScraper/assets/155127411/d0cba41b-ded0-451b-81e5-767ec8647e3a)
여기서 보면 1080px로 제공되는 것이 맞는 거 같지만요ㅠㅠ

**Comment by ilotoki0804** [comment]
프롤로그같은 무료로 소장 가능한 에피소드의 경우에는 모바일 기준으로 내 서재 > 소장 작품 > 소장 클릭하면 무료로 소장 처리되는 것으로 알고 있는데 시도해보셨나요?

**Comment by kkkkk-123** [comment]
네ㅠㅠ 소장 중이에요!
![서재](https://github.com/ilotoki0804/WebtoonScraper/assets/155127411/adca0d04-2165-4398-ac8a-a7c153db1870)

**Comment by ilotoki0804** [comment]
웹툰 폴더가 남은 상태에서 그대로 다시 다운로드하면 스킵될 텐데 전에 다운로드되었던 웹툰 폴더를 삭제(혹은 이름 변경)하셨나요?

**Comment by kkkkk-123** [comment]
삭제 후 다시 진행해 봤는데 720이에요..!

**Comment by ilotoki0804** [comment]
그렇다면 다음 코드를 실행하고 결과값을 공유해주실 수 있나요?

```python
from WebtoonScraper.scrapers import LezhinComicsScraper

if __name__ == "__main__":
    bearer = 'Bearer ...'
    scraper = LezhinComicsScraper('gahu_r', bearer=bearer)  # 소장한 무료 에피소드가 있는 웹툰을 gahu_r의 위치에 붙여넣으세요.
    scraper.get_paid_episode = True
    scraper.fetch_user_infos()
    print(scraper.purchased_episodes)
```

**Comment by kkkkk-123** [comment]
Traceback (most recent call last):
  File "C:\Users\USER\test\l.py", line 7, in <module>
    scraper.fetch_user_infos()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\WebtoonScraper\scrapers\A_scraper.py", line 59, in wrapper
    return_value = f(self, *args, reload=reload, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\WebtoonScraper\scrapers\J_lezhin_comics.py", line 196, in fetch_user_infos
    view_episodes_set = {int(episode_int_id) for episode_int_id in data['history']}
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by ilotoki0804** [comment]
전에 [이 코드](https://github.com/ilotoki0804/WebtoonScraper/issues/3#issuecomment-1872670045)를 사용했을 때에도 같은 오류가 났었나요?

**Comment by kkkkk-123** [comment]
넵 Bearer 쓰고 실행했을 때 오류가 뜹니다!

Traceback (most recent call last):
  File "C:\Users\USER\test\l.py", line 7, in <module>
    scraper.fetch_user_infos()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\WebtoonScraper\scrapers\A_scraper.py", line 59, in wrapper
    return_value = f(self, *args, reload=reload, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\WebtoonScraper\scrapers\J_lezhin_comics.py", line 196, in fetch_user_infos
    view_episodes_set = {int(episode_int_id) for episode_int_id in data['history']}
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by ilotoki0804** [comment]
쿠키 때문인 것 같네요. 쿠키 넣어보시고 다시 한 번 해봐 주세요.

**Comment by kkkkk-123** [comment]
C:\Users\USER\test>l.py
Traceback (most recent call last):
  File "C:\Users\USER\test\l.py", line 8, in <module>
    scraper.fetch_user_infos()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\WebtoonScraper\scrapers\A_scraper.py", line 59, in wrapper
    return_value = f(self, *args, reload=reload, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\WebtoonScraper\scrapers\J_lezhin_comics.py", line 196, in fetch_user_infos
    view_episodes_set = {int(episode_int_id) for episode_int_id in data['history']}
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

![11](https://github.com/ilotoki0804/WebtoonScraper/assets/155127411/3ceea685-0a21-46f2-b2f7-27118add9060)

이렇게 했는데 오류가 나요ㅠㅠ

**Comment by kkkkk-123** [comment]
C:\Users\USER\test>l.py
Traceback (most recent call last):
  File "C:\Users\USER\test\l.py", line 8, in <module>
    scraper.fetch_user_infos()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\WebtoonScraper\scrapers\A_scraper.py", line 59, in wrapper
    return_value = f(self, *args, reload=reload, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\WebtoonScraper\scrapers\J_lezhin_comics.py", line 196, in fetch_user_infos
    view_episodes_set = {int(episode_int_id) for episode_int_id in data['history']}
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

![222](https://github.com/ilotoki0804/WebtoonScraper/assets/155127411/62258c77-22ae-429e-95c5-6f48db2deaca)

**Comment by ilotoki0804** [comment]
다음 코드를 실행하고 결과를 공유해주실 수 있나요? 개인정보가 있는 경우에는 가려주세요.
```python
from pprint import pprint
from WebtoonScraper.scrapers import LezhinComicsScraper

scraper = LezhinComicsScraper('WEBTOON_ID_HERE', bearer=bearer, cookie=cookie)
scraper.fetch_all()
url = f"https://www.lezhin.com/lz-api/v2/users/5000000000000000/contents/{scraper.webtoon_int_id}"
data = scraper.requests.get(url).json()
pprint(data)
```

**Comment by kkkkk-123** [comment]
C:\Users\USER\test>l.py
Traceback (most recent call last):
  File "C:\Users\USER\test\l.py", line 4, in <module>
    scraper = LezhinComicsScraper('gahu_r', bearer=bearer, cookie=cookie)
                                                   ^^^^^^
NameError: name 'bearer' is not defined

**Comment by ilotoki0804** [comment]
bearer와 cookie를 적용해 주세요.

**Comment by kkkkk-123** [comment]
![11](https://github.com/ilotoki0804/WebtoonScraper/assets/155127411/58cb0f28-ce6d-40dd-84a6-2f9ec517cacc)
이렇게 쓰고 실행했을 때 위의 오류가 떴어요.

**Comment by ilotoki0804** [comment]
다음과 같이 코드를 짜 주세요.
```python
from pprint import pprint
from WebtoonScraper.scrapers import LezhinComicsScraper

bearer = '...'
cookie = '...'
scraper = LezhinComicsScraper('WEBTOON_ID_HERE', bearer=bearer, cookie=cookie)
scraper.fetch_all()
url = f"https://www.lezhin.com/lz-api/v2/users/5000000000000000/contents/{scraper.webtoon_int_id}"
data = scraper.requests.get(url).json()
pprint(data)
```

**Comment by kkkkk-123** [comment]
C:\Users\USER\test>l.py
{'code': 0,
 'data': {'history': None,
          'latestViewedEpisode': None,
          'notification': False,
          'preferred': 'none',
          'purchased': [],
          'subscribed': False},
 'description': '정상 처리 되었습니다.'}

**Comment by ilotoki0804** [comment]
버그가 수정되었고 다음 버전에 반영될 예정입니다.
문제가 발생한 이유는 열람한 회차가 없었기 때문입니다.
만약 지금 코드를 사용하고 싶으시다면 아무 회차나 하나 선택해서 보고 다시 코드를 실행하면 문제가 해결될 겁니다.

**Comment by kkkkk-123** [comment]
네 고생 많으셨어요!! 열람하니까 히스토리가 생기네요!

C:\Users\USER\test>l.py
{'code': 0,
 'data': {'history': ['6003432835907584', '6270393188745216'],
          'latestViewedEpisode': 6270393188745216,
          'notification': False,
          'preferred': 'none',
          'purchased': [],
          'subscribed': False},
 'description': '정상 처리 되었습니다.'}

**Comment by ilotoki0804** [comment]
이제 1080p 다운로드 잘 되시나요?

**Comment by kkkkk-123** [comment]
이미지가 안 받아져요! 폴더가 없어요ㅠㅠ

C:\Users\USER\test>l.py
WARNING:root:Unusable or not for free episode will be skipped. Following epsodes will be skipped: 2화, 3화, 4화, 5화, 6 화, 7화, 8화, 9화, 10화, 11화, 12화, 13화, 14화, 15화, 16화, 17화, 18화, 19화, 20화, 21화, 22화, 23화, 1부 최종화, 2부 1화, 26화, 27화, 28화, 29화, 30화, 31화, 32화, 33화, 34화, 35화, 36화, 37화, 38화, 39화, 40화, 41화, 42화, 43화, 44화, 45화, 46화, 47화, 최종화, 외전 1화, 외전 2화, 외전 3화, 외전 4화, 외전 5화, 외전 6화, 외전 7화, 외전 8화, 외전 9화, 외전  최종화
{'code': 0,
 'data': {'history': ['5257470432575488',
                      '5337533576970240',
                      '5138866934972416',
                      '5314469404934144',
                      '5524328972877824',
                      '5517681081253888',
                      '5790323933773824',
                      '6722190511505408',
                      '6166825138978816',
                      '6195720211464192',
                      '5926092645662720',
                      '4652661678604288',
                      '5799316924203008',
                      '5031677849305088',
                      '6446719081185280',
                      '5820542566072320',
                      '6059118038941696',
                      '4800847770091520',
                      '5893516925665280',
                      '5778588654436352',
                      '5661075458293760',
                      '4716581494784000',
                      '5956545792507904',
                      '6456911752134656',
                      '6240707812327424',
                      '5569189327470592',
                      '4570606374027264',
                      '5496698215137280',
                      '5650513269161984',
                      '6423953947820032',
                      '5372907214929920',
                      '4812576267239424',
                      '6123494733316096',
                      '5404702770266112',
                      '5053387237556224',
                      '5038127713681408',
                      '6124441966018560',
                      '6039211106172928',
                      '6258758346145792',
                      '6418127784312832',
                      '5281745558896640',
                      '5726969217220608',
                      '4754550058975232',
                      '5469478343999488',
                      '5858389193457664',
                      '5857975475699712',
                      '5964001788624896',
                      '4704908693274624',
                      '6073490072207360',
                      '5135851968593920',
                      '5818017650114560',
                      '5331040899760128',
                      '4862014263197696',
                      '5597103842459648',
                      '5108863364562944',
                      '4688475988492288',
                      '6212049951850496',
                      '5849080136531968',
                      '5924150469001216',
                      '5654146073821184'],
          'latestViewedEpisode': 5849080136531968,
          'notification': False,
          'preferred': 'none',
          'purchased': [4570606374027264,
                        6456911752134656,
                        4754550058975232,
                        5337533576970240,
                        5818017650114560,
                        5857975475699712,
                        5517681081253888,
                        5031677849305088,
                        5893516925665280,
                        5858389193457664,
                        4688475988492288,
                        6124441966018560,
                        5281745558896640,
                        5726969217220608,
                        5650513269161984,
                        5135851968593920,
                        5138866934972416,
                        5790323933773824,
                        5799316924203008,
                        5053387237556224,
                        6039211106172928,
                        5038127713681408,
                        6418127784312832,
                        6195720211464192,
                        6212049951850496,
                        4800847770091520,
                        5372907214929920,
                        6258758346145792,
                        5956545792507904,
                        5964001788624896,
                        5524328972877824,
                        5778588654436352,
                        5108863364562944,
                        5820542566072320,
                        4862014263197696,
                        5314469404934144,
                        4716581494784000,
                        5496698215137280,
                        5926092645662720,
                        5257470432575488,
                        6722190511505408,
                        5569189327470592,
                        5924150469001216,
                        6240707812327424,
                        6073490072207360,
                        5597103842459648,
                        6446719081185280,
                        5469478343999488,
                        6166825138978816,
                        6423953947820032,
                        5331040899760128,
                        4652661678604288,
                        6123494733316096,
                        6059118038941696,
                        4704908693274624,
                        4812576267239424,
                        5654146073821184,
                        5404702770266112,
                        5661075458293760,
                        5849080136531968],
          'subscribed': False},
 'description': '정상 처리 되었습니다.'}

**Comment by ilotoki0804** [comment]
다음 코드를 사용해 보세요.
```python
from WebtoonScraper.scrapers import LezhinComicsScraper

if __name__ == "__main__":
    bearer = 'Bearer ...'
    cookie = "..."
    scraper = LezhinComicsScraper('gahu_r', bearer=bearer)  # 소장한 무료 에피소드가 있는 웹툰을 gahu_r의 위치에 붙여넣으세요.
    scraper.get_paid_episode = True
    scraper.fetch_user_infos()
    scraper.download_webtoon()
```

**Comment by kkkkk-123** [comment]
잘 받아지는데 1화는 720픽셀이에요!

C:\Users\USER\test>l.py
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
downloading 4화:   7%|████▍

**Comment by ilotoki0804** [comment]
로그로 보았을 때는 해당 회차는 원래 720p인 게 맞는 것 같습니다. 아니더라도 WebtoonScraper로는 다운로드 불가능해 보입니다. 레진코믹스 앱으로 볼 때는 1080p로 볼 수 있는 에피소드인가요?

**Comment by kkkkk-123** [comment]
PC 웹상으로는 1080이 맞는데 앱으로는 720일 수도 있겠네요. 앱은 확인하는 방법을 몰라서.. ㅠㅠ

**Comment by ilotoki0804** [comment]
안타깝게도 해당 문제를 해결하기는 힘들 것 같습니다. 이슈는 닫겠습니다.
새해 복 많이 받으세요 :)

**Comment by ilotoki0804** [comment]
기존 코드에 버그가 있었네요... 2.3.6으로 업데이트하시고 되는지 확인해 주실 수 있나요?

**Comment by kkkkk-123** [comment]
업데이트하고 실행하니까 오류가 나요! 

![11](https://github.com/ilotoki0804/WebtoonScraper/assets/155127411/bb4b7951-0fd4-43ce-a996-88c734d8afe3)

C:\Users\USER\test>l.py
Traceback (most recent call last):
  File "C:\Users\USER\test\l.py", line 8, in <module>
    scraper.fetch_user_infos()
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LezhinComicsScraper' object has no attribute 'fetch_user_infos'. Did you mean: 'fetch_user_informations'?

**Comment by ilotoki0804** [comment]
지난 버전에 `fetch_user_infos()` 메소드가 `fetch_user_informations`으로 이름이 바뀌어서 그렇습니다.
다음 코드를 사용하면 문제 없이 작동할 겁니다.
```python
from WebtoonScraper.scrapers import LezhinComicsScraper

if __name__ == "__main__":
    bearer = 'Bearer ...'
    cookie = "..."
    scraper = LezhinComicsScraper('WEBTOON ID HERE', bearer=bearer)
    scraper.get_paid_episode = True
    scraper.fetch_user_informations()
    print(scraper.purchased_episodes)
    scraper.download_webtoon()
```

**Comment by kkkkk-123** [comment]
와 1080px로 받아져요! 너무 감사드려요!! 고생 많으셨습니다!ㅠㅠ
![11](https://github.com/ilotoki0804/WebtoonScraper/assets/155127411/74ce7bd7-39c5-4ab5-8b11-7753e9bd2694)

**Comment by ilotoki0804** [comment]
좋네요. WebtoonScraper 잘 이용해 주셔서 감사합니다 :)

**Comment by kkkkk-123** [comment]
감사히 잘 쓸게요!! 새해 복 많이 받으세요!
