### ISSUE TITLE
레진코믹스 업뎃으로 인한것인지 invalid self. webtoon_id 에러가 납니다.

### ISSUE THREAD

**Issue by thesailman** [ilotoki0804/WebtoonScraper#8]
일단 이 좋은걸 만들어주셔서, 지금까지 잘 써오고있었음에 먼저 감사를 드립니다.

legacy how to use,에 써져있던 방식. 즉 과거 설명으로 써있던 

webtoon download dr_hearthstone -p lezhin_comics --bearer "YOUR BEARER HERE"

해당방식을 사용하거나, 

webtoon download https://www.lezhin.com/ko/comic/their_ark --bearer "Bearer ****" --get-paid-episode -r 39~

사용시, 6월달까지 멀쩡했던 방식임에도 불구하고, 현 8월에 써보니 위 제목처럼 에러가 납니다.
변경사항이 있나 찾아봤음에도 보이지가 않아, 이곳에 질문을 올립니다.
스크래퍼 버전은 3.6.0버전입니다.

(그리고 unshuffler 어떻게 사용하는지도 여쭤봐도 되겠습니까..?)

**Comment by thesailman** [comment]
C:\Users\Administrator>webtoon download "https://www.lezhin.com/ko/comic/dr_hearthstoe"
ERROR    InvalidWebtoonIdError: Invalid webtoon ID: 'dr_hearthstoe' for LezhinComicsScraper.

C:\Users\Administrator>webtoon download "dr_hearthstone"
ERROR    InvalidPlatformError: Failed to retrieve webtoon platform from URL: dr_hearthstone

C:\Users\Administrator>webtoon download -p lezhin_comics "dr_hearthstone"
ERROR    AssertionError: Invalid self.webtoon_id='dr_hearthstone'.

self id  뚫어볼려고 시도했던 코드들입니다. 가르침을 내려주시면 대단히 감사드리겠습니다.

**Comment by ilotoki0804** [comment]
레진코믹스가 업데이트되면서 깨진 것 같아 보입니다.
지금 WebtoonScraper 새 버전 관련 업데이트 때문에 바로는 해결하지는 못 하겠지만, 곧 해결하겠습니다.
언셔플러에 대해 어떤 부분이 궁금하신 건지 잘은 모르겠지만 일단 설명드리자면 언셔플링은 웹툰은 다운로드받은 직후에 이어서 작동하며, 별도의 사용자의 개입이 필요하진 않고 자동으로 이루어집니다.

**Comment by thesailman** [comment]
아 감사합니다. 제가 무엇인가를 잘못한게 아니군요. 해결해주심에 대단히 감사드립니다.
그리고 제가 궁금한것이 unshuffler가 레진코믹스 일부만화를 들어가서 이미지파일을 추출해서 보면, 섞여서 보이기에, 이 unshullfer가 다운받을떄 추출한 이미지파일 순서가 섞여서 보이는걸 원상태로 보여주는것일지, 아님 다른것일지 여쭙습니다.

**Comment by ilotoki0804** [comment]
레진코믹스의 일부 웹툰은 셔플링이 적용되어 있습니다. 이러한 웹툰들은 그냥 다운로드받으면 `웹툰이름(webtoonid, shuffled)`의 형식으로 다운로드가 됩니다.
이 웹툰들은 다운로드받은 직후 언셔플러에 의해 언셔플링이 일어납니다. 그러면 `웹툰이름(webtoonid)`라는 이름의 폴더가 생성되는데, 그 웹툰 폴더가 언셔플된 폴더(i.e. 일반 웹툰 폴더)입니다.
그러니 말씀하신 대로 언셔플러는 'shuffled 웹툰 디렉토리'를 '일반 웹툰 디렉토리'로 언셔플해주는 것이 맞습니다.

**Comment by thesailman** [comment]
감사합니다!
