### ISSUE TITLE
전의 문제사항을 해결해주셔서 감사하며, 추가질문사항이 있습니다,

### ISSUE THREAD

**Issue by thesailman** [ilotoki0804/WebtoonScraper#9]
먼저 pre릴리즈 버전을 받아서 적용시켜보니, 다운이 다시 됩니다. 감사합니다!

https://www.lezhin.com/ko/comic/cartoon_hero 나 현재 레진에서 연재되고있는 최신웹툰(https://www.lezhin.com/ko/comic/hotcouple등등) 같은경우는, 다운시 이미지가 뒤죽박죽으로 섞여서 보입니다.

과거작품이나 타 플랫폼에서 수입된 작품들은 괜찮은 것으로 보아, 아마 레진측에서 브라우저에서 보여주는 이미지랑 추출이미지에 뭔가 설정을 한듯한데, 혹시 해결이 가능하실지 질문드려도 되겠습니까?(전에 unshuffler 질문드렸던 이유가 이렇게 섞여나와서 혹 unshuffle가 원래대로 보여주나.. 했는데 그건 아니더라구요)

https://github.com/ImSejin/lezhin-comics-downloader/issues/201
여기에 따르면 무슨 법칙 어쩌구를 사용해서 돌려놓을수가 있다고 하는데, 일단 웹툰스크래퍼 버전업때문에 바쁘실때 질문 많이드려서 죄송하며, 혹 나중에 시간나실때 확인가능하실지 여쭙습니다.

**Comment by ilotoki0804** [comment]
해야 할 일은 그냥 다운로드가 완료될 때까지 차분히 기다리시기만 하면 됩니다.
예를 들어 말씀하신 [lezhin.com/ko/comic/cartoon_hero](https://www.lezhin.com/ko/comic/cartoon_hero)를 다운로드한다고 하면, 그냥 일반적인 `webtoon download "https://www.lezhin.com/ko/comic/cartoon_hero"` 명령어를 치고 그냥 기다리시면 `4컷용사(cartoon_hero)`라고 되어 있는 웹툰 폴더와 `4컷용사(cartoon_hero, shuffled)`라고 되어 있는 폴더 두 개가 나타날 겁니다.
`4컷용사(cartoon_hero)` 폴더 안에 있는 내용은 섞여져 있지 않으니 그걸 사용하시면 됩니다.

**Comment by thesailman** [comment]
> 해야 할 일은 그냥 다운로드가 완료될 때까지 차분히 기다리시기만 하면 됩니다. 예를 들어 말씀하신 [lezhin.com/ko/comic/cartoon_hero](https://www.lezhin.com/ko/comic/cartoon_hero)를 다운로드한다고 하면, 그냥 일반적인 `webtoon download "https://www.lezhin.com/ko/comic/cartoon_hero"` 명령어를 치고 그냥 기다리시면 `4컷용사(cartoon_hero)`라고 되어 있는 웹툰 폴더와 `4컷용사(cartoon_hero, shuffled)`라고 되어 있는 폴더 두 개가 나타날 겁니다. `4컷용사(cartoon_hero)` 폴더 안에 있는 내용은 섞여져 있지 않으니 그걸 사용하시면 됩니다.

아 그게 무한루프가 일어나서 선생님 말씀처럼 가만히 있으면 될줄 알았는데, 끝나지가 않더라고요.
그래가지고 shuffle 폴더와 안달린폴더가 생성되는데, shuff폴더에는 뒤죽박죽 파일이 다 들어가 있는데, 그 셔플 안달린거는 파일이 대표이미지 1개만 들어가있더라고요.

이상한건 bearer 없이 그냥 "링크" 다운로드 하면 1화만 받아지긴 해도 그건 셔플이 되는데, bearer 한다음 전체화수를 받으면 무한루프가 뜨면서 웹툰대표이미지 1 개만 들어있는 상황이 계속 생기더라고요.
그래서 혹 언셔플러가 이게 아닌가 하였습니다.

이슈 새로 열겠습니다. 확인해주시면 감사하겠습니다.

**Comment by thesailman** [comment]
[새 텍스트 문서 (2).txt](https://github.com/user-attachments/files/16564114/2.txt)

일단 .py실행시 무한루프에 걸리는 걸 복붙해놨습니다.

----사용한 .py는 

from WebtoonScraper.scrapers import LezhinComicsScraper

bearer = "Bearer예문"
cookie = None  # 성인 웹툰을 다운로드받을 경우 설정할 것.

scraper = LezhinComicsScraper.from_url(
    "https://www.lezhin.com/ko/comic/strong",
    bearer=bearer,
    cookie=cookie,
)
scraper.download_webtoon()

-----입니다.

해당.py를 사용하지 않고,  webtoon download "https://www.lezhin.com/ko/comic/cartoon_hero" 처럼 사용시, 1화만 다운이 되긴 하나, 그뒤에 unshuffle가 작동하여 폴더가 2개 생성됩니다.

밑에 이슈보니까 2.2버전? 그때쯤에 알려주신 해결방법이 있어서 보긴 했는데, 내용이 달라서 잘 모르겠기에 추가로 올립니다.

**Comment by ilotoki0804** [comment]
굳이 파이썬 스크립트를 이용할 필요는 없습니다. 1화만 다운로드가 된 이유는 언셔플러 때문은 아니고 bearer가 없어서이기 때문에 그냥 `webtoon download "https://www.lezhin.com/ko/comic/cartoon_hero" --bearer "Bearer ...."`를 사용하시면 됩니다.
무한 루프가 발생하는 이유는 파이썬 스크립트를 `if __name__ == "__main__"` 없이 사용하였기 때문입니다. 해당 가드를 사용하면 해결됩니다.

수정하면 다음과 같습니다.

```python
from WebtoonScraper.scrapers import LezhinComicsScraper

bearer = "Bearer예문"
cookie = None # 성인 웹툰을 다운로드받을 경우 설정할 것.

if __name__ == "__main__":
    scraper = LezhinComicsScraper.from_url(
        "https://www.lezhin.com/ko/comic/strong",
        bearer=bearer,
        cookie=cookie,
    )
    scraper.download_webtoon()
```

위의 CLI 명령어와 파이썬 스크립트 중에 하나만 사용하셔도 됩니다.

**Comment by ilotoki0804** [comment]
> --bearer "bearer 어쩌구"사용시 에러가 뜨더라고요.

bearer를 사용하실 때 오류가 발생한다면 오류 메시지 전체를 보여주세요.

**Comment by thesailman** [comment]
일단 선생님께서 알려주신 것처럼, 밑에 가드문구 추가해서 했더니 멀쩡하게 작동됩니다. 감사합니다!
덕분에 다시 웹툰 받을수 있어요!!!
그리고 밑에 해당 오류들은 정리해놨습니다. 시간나실떄 읽어주시면 매우 감사드리겠습니다.

> > --bearer "bearer 어쩌구"사용시 에러가 뜨더라고요.
> 
> bearer를 사용하실 때 오류가 발생한다면 오류 메시지 전체를 보여주세요.

--------------------
1. bearer 사용시 뜨는 에러문구 

아래의 오류문장들은, 각 설명된 프로그램에서 webtoon download https://www.lezhin.com/ko/comic/strong --bearer "어쩌구"
실행시 뜨는 오류입니다.

**Python 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> webtoon download https://www.lezhin.com/ko/comic/strong --bearer "Bearer 어쩌구"
  File "<stdin>", line 1
    webtoon download https://www.lezhin.com/ko/comic/strong --bearer "어쩌구"
            ^^^^^^^^
SyntaxError: invalid syntax
>>> webtoon download "https://www.lezhin.com/ko/comic/cartoon_hero" --bearer "어쩌구"
  File "<stdin>", line 1
    webtoon download "https://www.lezhin.com/ko/comic/cartoon_hero" --bearer "어쩌구"
            ^^^^^^^^
SyntaxError: invalid syntax**
>>>


**가 python에서 뜨는것이며,** 

**C:\Users\Administrator>webtoon download "https://www.lezhin.com/ko/comic/cartoon_hero" --bearer "Bearer어쩌구"
usage: WebtoonScraper [-h] [--mock] [--version] [-v] {download,merge,concat} ...
WebtoonScraper: error: unrecognized arguments: --bearer Bearer 어쩌구**


**는 cmd에 webtoon 쳐서 실행시 뜨는겁니다.** 
앞서 설명하였듯이, webtoon download https://www.lezhin.com/ko/comic/strong 만 치면 1화만 다운되나, 작동은 잘 됩니다.

-------------------
2.   파이썬 스크립트를 꼭 이용은 안해도 되지만, exe프로그램쓰면 에러나는것도 있고, 해당프로그램 shuffle 문제도 발생해서 . py로 쓰는게 낫더라고요.
[pyinstaller.zip](https://github.com/user-attachments/files/16569057/pyinstaller.zip)

해당 exe파일인데, 아마 5월안가 6월달에 받았었던 것으로 기억합니다.
근데 shuffle 파일 받았으면, 이 파일들을 다시 unshuffle화 할수 있을까요? 유료화된 회차라 지금은 다운을 못할텐데 unshuffle 만 가능한가 궁금해서 그렇습니다.
--------------------
3. 그래서 위에 설명하였던 문제들로 인하여, exe파일에서 shuffle 작동 안되었던 것도 있었고, 백업용으로만 받아놨었기에 안되는 줄로만 알았습니다..

**Comment by ilotoki0804** [comment]
유료화 웹툰은 다음과 같이 설정하면 다운로드가 가능합니다.
```console
webtoon download "<다운로드받을 URL>" --options bearer="Bearer ..." download_paid=true
```
\* 아직 WebtoonScraper 4 문서화가 진행 중이라 관련 자료가 없지만, 곧 문서도 나올 겁니다.

**Comment by thesailman** [comment]
> 유료화 웹툰은 다음과 같이 설정하면 다운로드가 가능합니다.
> 
> ```
> webtoon download "<다운로드받을 URL>" --options bearer="Bearer ..." download_paid=true
> ```
> 
> * 아직 WebtoonScraper 4 문서화가 진행 중이라 관련 자료가 없지만, 곧 문서도 나올 겁니다.

```
      ```
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\download_webtoon - 복사본.py", line 12, in <module>
    scraper.download_webtoon(episode_no_range=(2, 5))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\WebtoonScraper\scrapers\_01_scraper.py", line 178, in download_webtoon
    asyncio.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\WebtoonScraper\scrapers\_07_lezhin_comics.py", line 102, in async_download_webtoon
    await super().async_download_webtoon(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\WebtoonScraper\scrapers\_01_scraper.py", line 213, in async_download_webtoon
    self.fetch_all()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\WebtoonScraper\scrapers\_07_lezhin_comics.py", line 110, in fetch_all
    super().fetch_all(reload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\WebtoonScraper\scrapers\_01_scraper.py", line 154, in fetch_all
    self.fetch_episode_information(reload=reload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\WebtoonScraper\scrapers\_01_helpers.py", line 134, in wrapper
    return_value = f(self, *args, reload=reload, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\WebtoonScraper\scrapers\_07_lezhin_comics.py", line 170, in fetch_episode_information
    self._parse_episode_information(data["meta"]["episodes"])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\WebtoonScraper\scrapers\_07_lezhin_comics.py", line 378, in _parse_episode_information
    free_dates.append(episode["freedAt"])
KeyError: 'freedAt'
```
```


4컷용사 다운시 선생님께서 말씀하신것처럼 뒤에 paid를 붙여도, 범위지정해서 무료회차만 받게해도,새로 달아주신 방식으로 다운을 하여도 freedat이라는 에러가 계속 뜨면서 다운을 못하게 됩니다.
일단 스크래퍼4 나올때까지 기다리는게 나을까요? 무료화 웹툰들은 잘 받아져서 급하지는 않아서 그렇습니다.

**Comment by ilotoki0804** [comment]
수정본이 나왔고, 다음 프리릴리즈에 포함될 예정입니다.

> 일단 스크래퍼4 나올때까지 기다리는게 나을까요?

일단 오류가 있다면 말씀해주시는 게 낫습니다. 그래야 더 빨리 고쳐질 테니까요.
